### ISSUE TITLE
bugs.almalinux.org issues

### ISSUE THREAD

**Issue by Bill-ColeUS** [AlmaLinux/wiki#7]
I have two issues with bugs.almalinux.org, but I can't access bugs.almalinux.org to report them there, so maybe someone from here can take a look.

1) email verifications are being sent via sendgrid, a major spammer and pretty much blocked world-wide. Could you please find a better way to send emails?

2) since the verification email was rejected because it came via sendgrid, I have no way to verify my email address, because even if I put a manual white-list, there is no method to request another verification email.

I'd appreciate your input.

Thank you.

**Comment by ezamriy** [comment]
Hi!

1. I forwarded your wishes to the people responsible for this. Thanks for reporting.
2. Did you try to recover it with Password Reset? If it doesn't help, drop me a mail to my_github_username@cloudlinux.com from the email you've used for bugs.almalinux.org registration. I will either find a way to activate your account manually or will delete it so that you can register again.
